function Untitled = importCOVIDfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  UNTITLED = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as a table.
%
%  UNTITLED = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  Untitled = importfile("C:\Users\juerg\Documents\MATLAB\Projects\COVID19analysis\csse_covid_19_data\csse_covid_19_daily_reports\06-25-2020.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 16-Sep-2020 13:35:53

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 14);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["FIPS", "Admin2", "Province_State", "Country_Region", "Last_Update", "Lat", "Long_", "Confirmed", "Deaths", "Recovered", "Active", "Combined_Key", "Incidence_Rate", "CaseFatality_Ratio"];
opts.VariableTypes = ["double", "string", "categorical", "categorical", "datetime", "double", "double", "double", "double", "double", "double", "string", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Admin2", "Combined_Key"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Admin2", "Province_State", "Country_Region", "Combined_Key"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "Last_Update", "InputFormat", "yyyy-MM-dd HH:mm:ss");

% Import the data
Untitled = readtable(filename, opts);

end