function Untitled = importCOVIDfile2(filename, dataLines)
%IMPORTFILE Import data from a text file
%  UNTITLED = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as a table.
%
%  UNTITLED = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  Untitled = importfile("e:\Users\juerg\Documents\MATLAB\Projects\COVID19analysis\csse_covid_19_data\csse_covid_19_daily_reports\09-29-2020.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 30-Sep-2020 10:11:36

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = detectImportOptions(filename); % Detect import parameters
opts = delimitedTextImportOptions("NumVariables", 14);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["FIPS", "Admin2", "Province_State", "Country_Region", "Last_Update", "Lat", "Long_", "Confirmed", "Deaths", "Recovered", "Active", "Combined_Key", "Incidence_Rate", "CaseFatality_Ratio"];
opts.VariableTypes = ["char", "double", "char", "categorical", "datetime", "double", "double", "double", "double", "double", "double", "char", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["FIPS", "Province_State", "Combined_Key"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["FIPS", "Province_State", "Country_Region", "Combined_Key"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "Last_Update", "InputFormat", "yyyy-MM-dd HH:mm:ss");
opts = setvaropts(opts, "Admin2", "TrimNonNumeric", true);
opts = setvaropts(opts, "Admin2", "ThousandsSeparator", ",");

% Import the data
Untitled = readtable(filename, opts);

end